version: '3.8'

services:
  warehouse-db:
    image: postgres:15
    container_name: warehouse_db
    restart: always
    environment:
      POSTGRES_USER: ${WAREHOUSE_DB_USER}
      POSTGRES_PASSWORD: ${WAREHOUSE_DB_PASSWORD}
      POSTGRES_DB: ${WAREHOUSE_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - warehouse_pgdata:/var/lib/postgresql/data
    networks:
      - microservices-network

  checkout-db:
    image: postgres:15
    container_name: checkout_db
    restart: always
    environment:
      POSTGRES_USER: ${CHECKOUT_DB_USER}
      POSTGRES_PASSWORD: ${CHECKOUT_DB_PASSWORD}
      POSTGRES_DB: ${CHECKOUT_DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - checkout_pgdata:/var/lib/postgresql/data
    networks:
      - microservices-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservices-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - microservices-network

  api-gateway:
    image: nginx:alpine
    container_name: api_gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - warehouse-service
      - checkout-service
    networks:
      - microservices-network

  warehouse-service:
    build: ./warehouse-service
    container_name: warehouse_service
    depends_on:
      - warehouse-db
      - redis
      - elasticsearch
    networks:
      - microservices-network
    ports:
      - "50051:50051" 

  checkout-service:
    build: ./checkout-service
    container_name: checkout_service
    depends_on:
      - checkout-db
      - redis
      - elasticsearch
    networks:
      - microservices-network
    ports:
      - "50052:50052" 

volumes:
  warehouse_pgdata:
  checkout_pgdata:
  redis_data:
  elasticsearch_data:

networks:
  microservices-network:
