// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: api/warehouse.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockRequest) Reset() {
	*x = StockRequest{}
	mi := &file_api_warehouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockRequest) ProtoMessage() {}

func (x *StockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockRequest.ProtoReflect.Descriptor instead.
func (*StockRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_proto_rawDescGZIP(), []int{0}
}

func (x *StockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateStockRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductId        string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	QuantityToDeduct int32                  `protobuf:"varint,2,opt,name=quantity_to_deduct,json=quantityToDeduct,proto3" json:"quantity_to_deduct,omitempty"`
	Revert           bool                   `protobuf:"varint,3,opt,name=revert,proto3" json:"revert,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_api_warehouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_api_warehouse_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateStockRequest) GetQuantityToDeduct() int32 {
	if x != nil {
		return x.QuantityToDeduct
	}
	return 0
}

func (x *UpdateStockRequest) GetRevert() bool {
	if x != nil {
		return x.Revert
	}
	return false
}

type StockResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,2,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StockResponse) Reset() {
	*x = StockResponse{}
	mi := &file_api_warehouse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockResponse) ProtoMessage() {}

func (x *StockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_warehouse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockResponse.ProtoReflect.Descriptor instead.
func (*StockResponse) Descriptor() ([]byte, []int) {
	return file_api_warehouse_proto_rawDescGZIP(), []int{2}
}

func (x *StockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StockResponse) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *StockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_warehouse_proto protoreflect.FileDescriptor

const file_api_warehouse_proto_rawDesc = "" +
	"\n" +
	"\x13api/warehouse.proto\x12\twarehouse\"I\n" +
	"\fStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"y\n" +
	"\x12UpdateStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12,\n" +
	"\x12quantity_to_deduct\x18\x02 \x01(\x05R\x10quantityToDeduct\x12\x16\n" +
	"\x06revert\x18\x03 \x01(\bR\x06revert\"r\n" +
	"\rStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\x12available_quantity\x18\x02 \x01(\x05R\x11availableQuantity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xa3\x01\n" +
	"\x10WarehouseService\x12G\n" +
	"\x12CheckAndBlockStock\x12\x17.warehouse.StockRequest\x1a\x18.warehouse.StockResponse\x12F\n" +
	"\vUpdateStock\x12\x1d.warehouse.UpdateStockRequest\x1a\x18.warehouse.StockResponseBIZGgithub.com/ramiroschettino/Go-Store-Microservices/warehouse-service/apib\x06proto3"

var (
	file_api_warehouse_proto_rawDescOnce sync.Once
	file_api_warehouse_proto_rawDescData []byte
)

func file_api_warehouse_proto_rawDescGZIP() []byte {
	file_api_warehouse_proto_rawDescOnce.Do(func() {
		file_api_warehouse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_warehouse_proto_rawDesc), len(file_api_warehouse_proto_rawDesc)))
	})
	return file_api_warehouse_proto_rawDescData
}

var file_api_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_warehouse_proto_goTypes = []any{
	(*StockRequest)(nil),       // 0: warehouse.StockRequest
	(*UpdateStockRequest)(nil), // 1: warehouse.UpdateStockRequest
	(*StockResponse)(nil),      // 2: warehouse.StockResponse
}
var file_api_warehouse_proto_depIdxs = []int32{
	0, // 0: warehouse.WarehouseService.CheckAndBlockStock:input_type -> warehouse.StockRequest
	1, // 1: warehouse.WarehouseService.UpdateStock:input_type -> warehouse.UpdateStockRequest
	2, // 2: warehouse.WarehouseService.CheckAndBlockStock:output_type -> warehouse.StockResponse
	2, // 3: warehouse.WarehouseService.UpdateStock:output_type -> warehouse.StockResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_warehouse_proto_init() }
func file_api_warehouse_proto_init() {
	if File_api_warehouse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_warehouse_proto_rawDesc), len(file_api_warehouse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_warehouse_proto_goTypes,
		DependencyIndexes: file_api_warehouse_proto_depIdxs,
		MessageInfos:      file_api_warehouse_proto_msgTypes,
	}.Build()
	File_api_warehouse_proto = out.File
	file_api_warehouse_proto_goTypes = nil
	file_api_warehouse_proto_depIdxs = nil
}
